#!/bin/sh
#
# ~/.xinitrc for Xfce4
#
## Locale
export LC_ALL=ja_JP.UTF-8
export LANGUAGE=ja_JP.UTF-8
export LANG=ja_JP.UTF-8

## Input Method - uim-mozc
#export GTK_IM_MODULE=uim
#export QT_IM_MODULE=uim
#export XMODIFIERS='@im=uim'
#export XIM=uim
## Input Method - fcitx-mozc
 export GTK_IM_MODULE=fcitx
 export QT_IM_MODULE=fcitx
 export XMODIFIERS='@im=fcitx'

## Start Input Method
/usr/local/bin/mozc start
#uim-xim &
 fcitx -r -d

## Disable Beep
xset -b

## Start Xfce4
exec startxfce4
