#!/bin/sh
#
# ~/.xinitrc for Xfce4
#
# Locale
export LC_ALL=ja_JP.UTF-8
export LANGUAGE=ja_JP.UTF-8
export LANG=ja_JP.UTF-8
# Input Method
export GTK_IM_MODULE=uim
export QT_IM_MODULE=uim
export XMODIFIERS='@im=uim'
export XIM=uim
# Start Mozc
/usr/local/bin/mozc start
uim-xim &
# Start Xfce4
exec startxfce4
